/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ae90f176-c7cd-47d5-ac54-58c8bc59c469",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_MRBMe7rmf",
    "aws_user_pools_web_client_id": "1pl688lqmd4th81nfrji9ldn0n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6qmt5hq25fdenbr6nrcq4zfigi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AWS_IAM"
};


export default awsmobile;
